### DISCUSSION TITLE
Multi Source models should be able to get loaded multiple times by the same source, using different columns

### DISCUSSION THREAD

**Discussion by tkirschke** [ScalefreeCOM/datavault4dbt#56] [Ideas]
It is a common case, where you want to load a hub (or any other multi source entity) out of multiple columns inside one staging object. In such a case, people would use the already available multi source function for those entities.

The problem is that this function is based on a dictionary, with the name of the source model as its keys. If the same stage would now be required multiple times, the information inside the dictionary would be overwritten, because keys inside a dictionary must be unique.

User input could look like this in the future:

```
source_models:
    - name:
      hk_column:
      bk_column:
    - name:
      hk_column:
      bk_column:
```
So instead of having a dictionary of dictionaries, we now have a list of dictionaries and added "name" as one of their keys
