### ISSUE TITLE
[FEATURE] Extract multiple columns from one prejoined object

### ISSUE THREAD

**Issue by tkirschke** [ScalefreeCOM/datavault4dbt#287]
**What additional value does this feature bring to the project?**

If I want to extract multiple columns from one prejoined object, e.g., for composite Business keys, Right now I need to define two separate prejoined columns.

**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I need multiple columns from a prejoined object.

**Describe the solution you'd like**

Right now, extracting multiple columns from the same object would look like this:

```
  prejoined_columns:
      businessid:
          ref_model: 'business_raw'
          bk: 'ID'
          this_column_name: 'ContractId'
          ref_column_name: 'ContractId'
      businessnumber:
          ref_model: 'business_raw'
          bk: 'number'
          this_column_name: 'ContractId'
          ref_column_name: 'ContractId'
```

I would like to have an additional, alternative way of defining prejoined columns:

```
  prejoined_columns:
      - extract_columns: 
           - id
           - number
        aliases:
           - businessid
           - businessnumber
        ref_model: 'business_raw'
        this_column_name: 'ContractId'
        ref_column_name: 'ContractId'
```
_aliases_ should be optional, but if given, must be the same length as _extract_columns_. 
_this_column_name_ & ref_column_name should still allow multiple columns
_ref_model_ should still be changeable to src_name & src_table
