### ISSUE TITLE
[BUG] Stage macro fails on databricks when hash_datatype is set to BINARY

### ISSUE THREAD

**Issue by kafkaguru** [ScalefreeCOM/datavault4dbt#295]
**Describe the bug**

When setting datavault4dbt.hash_datatype: BINARY, the resulting databricks query fails for the datavault4dbt.stage macro.

**Environment**

- dbt version: cloud 0.38.22
- datavault4dbt version: 1.8.1
- Database/Platform: databricks

**To Reproduce**

Please provide:
1. Model: 
```sql
select `cust_account_id`, `party_id`, `created_by`
from `catalog`.`schema`.`cust_accounts`
```
3. `dbt_project.yml`:
```yml
vars:
#Column Aliases
  datavault4dbt.ldts_alias: 'load_datetime'
  datavault4dbt.rsrc_alias: 'source'
  datavault4dbt.ledts_alias: 'load_end_datetime'
  datavault4dbt.snapshot_trigger_column: 'is_active'
  datavault4dbt.sdts_alias: 'source_datetime'
  datavault4dbt.is_current_col_alias: 'IS_CURRENT'
  datavault4dbt.deleted_flag_alias: 'deleted_flag'

  #Hash Configuration
  datavault4dbt.hash: SHA1
  datavault4dbt.hash_datatype: BINARY
  datavault4dbt.hashkey_input_case_sensitive: FALSE
  datavault4dbt.hashdiff_input_case_sensitive: TRUE
  
  # Stage Configuration
  datavault4dbt.copy_rsrc_ldts_input_columns: FALSE

  # General Configuration
  datavault4dbt.include_business_objects_before_appearance: false

  #Ghost Record Configuration
  datavault4dbt.beginning_of_all_times: {"databricks":"0001-01-01 00-00-00.001"}
  datavault4dbt.end_of_all_times: {"databricks":"8888-12-31 23-59-59.999"}
  datavault4dbt.timestamp_format: {"databricks":"yyyy-MM-dd HH:mm:ss.SSS"}
  
  datavault4dbt.beginning_of_all_times_date: {"databricks":"0001-01-01"}
  datavault4dbt.end_of_all_times_date: {"databricks":"8888-12-31"}
  datavault4dbt.date_format: {"databricks":"yyyy-mm-dd"}

  datavault4dbt.default_unknown_rsrc: 'SYSTEM'
  datavault4dbt.default_error_rsrc: 'ERROR'

  datavault4dbt.rsrc_default_dtype: {"databricks":"STRING"}
  datavault4dbt.timestamp_default_dtype: {"databricks":"TIMESTAMP"}
  datavault4dbt.stg_default_dtype: {"databricks":"STRING"}
  datavault4dbt.derived_columns_default_dtype: {"databricks":"STRING"}


  #Datatype specific default values
  datavault4dbt.error_value__STRING: '(error)'
  datavault4dbt.error_value_alt__STRING: 'e'
  datavault4dbt.unknown_value__STRING: '(unknown)'
  datavault4dbt.unknown_value_alt__STRING: 'u'
  datavault4dbt.unknown_value__numeric: '-1'
  datavault4dbt.error_value__numeric: '-2'
```
5. The datavault4dbt stage macro:
```yml-jinja
{%- set yaml_metadata -%}
source_model:
    'schema': 'cust_accounts'
hashed_columns:
    hk_customer_h:
        - cust_account_id
    hd_cust_accounts:
        is_hashdiff: true
        columns:
            - party_id
            - created_by

ldts: "CURRENT_TIMESTAMP()"
rsrc: '!schema.cust_accounts'
{%- endset -%}

{%- set metadata_dict = fromyaml(yaml_metadata) -%}


{{ datavault4dbt.stage(source_model=metadata_dict['source_model'],
                    ldts=metadata_dict['ldts'],
                    rsrc=metadata_dict['rsrc'],
                    hashed_columns=metadata_dict['hashed_columns'],
                    derived_columns=none,
                    missing_columns=none,
                    prejoined_columns=none,
                    include_source_columns=true) }}

```
7. The compile stage code:

```sql
IFNULL(SHA1(NULLIF(CAST(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(CONCAT(
        IFNULL((CONCAT('\"', REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(TRIM(CAST(CUST_ACCOUNT_ID AS STRING)), r'\\', r'\\\\'), '"', '\"'), '^^', '--'), '\"')), '^^')
        ), r'\n', '') 
        , r'\t', '') 
        , r'\v', '') 
        , r'\r', '') AS STRING), '^^')), CAST('0000000000000000000000000000000000000000' AS BINARY)) AS hk_customer_h,
```

7. The dbt error message
Database Error in model cust_accounts (models/staging/dv_staging/customer/cust_accounts.sql)
  [DATATYPE_MISMATCH.DATA_DIFF_TYPES] Cannot resolve "coalesce(sha1(nullif(CAST(regexp_replace(regexp_replace(regexp_replace(regexp_replace(concat(ifnull(concat(", replace(regexp_replace(regexp_replace(trim(CAST(CUST_ACCOUNT_ID AS STRING)), \\, \\\\, 1), ", ", 1), ^^, --), "), ^^)), \n, , 1), \t, , 1), \v, , 1), \r, , 1) AS STRING), ^^)), CAST(0000000000000000000000000000000000000000 AS BINARY))" due to data type mismatch: Input to `coalesce` should all be the same type, but it's ("STRING" or "BINARY"). SQLSTATE: 42K09;

**Expected behavior**

I expect the result of the sha1 function to also be cast to a binary so that the coalesce will operate on the same datatype, thus allowing the sql to proceed and store the hashkey as a binary datatype.
