### ISSUE TITLE
[BUG] Stage macro fails on ghost record creation in Databricks for binary datatype columns

### ISSUE THREAD

**Issue by kafkaguru** [ScalefreeCOM/datavault4dbt#299]
**Describe the bug**

When creating a stage view and setting `enable_ghost_records=true`, the resulting sql is invalid and fails to run the stage macro.

**Environment**

- dbt version: cloud
- datavault4dbt version: 1.8.1
- Database/Platform: Databricks

**To Reproduce**

1. Create a table with two columns: `id: string, data: binary`
2. Insert a row into the table
3. Create `source.yml` file and add the table to the file
4. Create a `stg_data.sql` file with the following code:

```yml
{%- set yaml_metadata -%}
source_model:
    "name": "table"
hashed_columns: 
    HK_ID_H:
        - id
    HD_TABLE:
        is_hashdiff: true
        columns:
            - id
            - data

ldts: "CURRENT_TIMESTAMP()"
rsrc: '!name.table'
{%- endset -%}

{%- set metadata_dict = fromyaml(yaml_metadata) -%}

{{ datavault4dbt.stage(source_model=metadata_dict['source_model'],
                    ldts=metadata_dict['ldts'],
                    rsrc=metadata_dict['rsrc'],
                    hashed_columns=metadata_dict['hashed_columns'],
                    derived_columns=metadata_dict['derived_columns'],
                    missing_columns=none,
                    prejoined_columns=none,
                    enable_ghost_records=true,
                    include_source_columns=true) }}
```
5. Run the dbt model (stage macro)
6. See the run fail with the error:
```
Database Error in model stg_data (models/staging/stg_data.sql)
  [WRONG_NUM_ARGS.WITHOUT_SUGGESTION] The `cast` requires 0 parameters but the actual number is 1. Please, refer to 'https://spark.apache.org/docs/latest/sql-ref-functions.html' for a fix. SQLSTATE: 42605;
```

When validating the resulting compiled sql, the sql is invalid due to:
```sql
unknown_values AS (
    SELECT
    '(unknown)' as id,
    CAST('') as data
)
```

Reading the documentation, it seems that we should be able to configure unknown values for a binary data type as follows:

```yml
vars:
  datavault4dbt.unknown_value__binary: '1111111111111111111111111111111111111111'
  datavault4dbt.unknown_value_alt__binary: '1111111111111111111111111111111111111111'
  datavault4dbt.error_value__binary: '2222222222222222222222222222222222222222'
  datavault4dbt.error_value_alt__binary: '2222222222222222222222222222222222222222'
```
(This was also tried with BINARY in all caps)

Excluding binary columns from the input model and setting `enable_ghost_records=false` both resolve the issue but is not ideal.

**Expected behavior**

Ghost records are created with unknown values for binary datatypes.
