### ISSUE TITLE
[BUG] Stage macro generates sql with ambiguous column name

### ISSUE THREAD

**Issue by lwehle** [ScalefreeCOM/datavault4dbt#337]
**Describe the bug**

After switching from 1.5.0 to 1.9.8 our sql generation for stage macros fails. CTE ldts_rsrc_data contains the ldts column two times, if the column is also used as a source for a derived column.

**Environment**

- dbt version: core 1.9.4
- datavault4dbt version: 1.9.8
- Database/Platform: snowflake

**To Reproduce**

Model sql:
```yaml
{%- set yaml_metadata -%}
source_model: 'TESTSOURCE'
derived_columns:
    EFFECTIVE_FROM: 'CDP_LOADDTS'
    ID: 'CAMPAIGNID'
ldts: 'CDP_LOADDTS'
rsrc: '!{{ model.name }}'
include_source_columns: true
enable_ghost_records: false
{%- endset -%}

{{ datavault4dbt.stage(yaml_metadata=yaml_metadata) }}
```

dbt_project.yml:
```yaml
datavault4dbt.ldts_alias: 'CDP_LOADDTS'
datavault4dbt.rsrc_alias: 'CDP_RECORD_SOURCE'
datavault4dbt.ldts_default_dtype: 'TIMESTAMP_LTZ'
datavault4dbt.copy_rsrc_ldts_input_columns: false
```

Compiled sql:
```sql
create or replace   view STAGE_GA.VAULT."TEST"
  copy grants as (
WITH
source_data AS (
    SELECT
        "CAMPAIGNID",
        "CDP_LOADDTS"
  FROM STAGE_GA.VAULT."TESTSOURCE"
  ),
ldts_rsrc_data AS (
  SELECT
    CAST( "CDP_LOADDTS" as TIMESTAMP_LTZ ) AS CDP_LOADDTS,  -- <- generated ldts
    CAST( 'TEST' as STRING ) AS CDP_RECORD_SOURCE,
        "CAMPAIGNID",
        "CDP_LOADDTS" -- <- used as source for derived column
  FROM source_data
),
derived_columns AS (SELECT
        "CDP_LOADDTS",
        "CDP_RECORD_SOURCE",
        "CAMPAIGNID",
        "CDP_LOADDTS",
  "CDP_LOADDTS" AS "EFFECTIVE_FROM",
    "CAMPAIGNID" AS "ID"
  FROM ldts_rsrc_data
),
columns_to_select AS (
    SELECT
        "CDP_LOADDTS",
        "CDP_RECORD_SOURCE",
        "CAMPAIGNID",
        "CDP_LOADDTS",
        "EFFECTIVE_FROM",
        "ID"
    FROM derived_columns
)
SELECT * FROM columns_to_select
  )
;
```

DBT error:
`SQL compilation error: ambiguous column name 'CDP_LOADDTS'`

**Expected behavior**

```sql
ldts_rsrc_data AS (
  SELECT
    CAST( "CDP_LOADDTS" as TIMESTAMP_LTZ ) AS CDP_LOADDTS,
    CAST( 'TEST' as STRING ) AS CDP_RECORD_SOURCE,
    "CAMPAIGNID"
  FROM source_data
),
```

**Additional context**

The model generation also fails, if include_source_columns is set to false. (`Expected a list of columns, got: []`) I don't think this behavior is intended.
