### ISSUE TITLE
Unknown and error values for calculated columns

### ISSUE THREAD

**Issue by lwehle** [ScalefreeCOM/datavault4dbt#63]
I get duplicate business keys (NULL) for hubs, if I use a calculated column as source.

dbt version: 1.4.5
datavault4dbt version: 1.0.16
database: snowflake

Steps to reproduce the issue:
Config values are set to default.

Staging model definition:
``` yaml
{%- set yaml_metadata -%}
source_model: abc
derived_columns:
  SAMPLE_CALCULATED_COLUMN:
    value: "'TEST_' || ID"
    datatype: string
  OTHER_STRING_COLUMN: NAME
ldts: LOADTIMESTAMP
rsrc: '!123'
{%- endset -%}
```

Generated sql (shortened):
``` sql
WITH

source_data AS (
    SELECT
     ...
      "ID",
      "NAME"
    FROM abc
  ),

ldts_rsrc_data AS (

  SELECT
    ...
    "ID",
    "NAME"
    FROM source_data

),

derived_columns AS (

  SELECT

  ...
  "NAME" AS "OTHER_STRING_COLUMN",
  'TEST_' || ID AS "SAMPLE_CALCULATED_COLUMN"
  FROM ldts_rsrc_data

),
unknown_values AS (

    SELECT

    ...
    '(unknown)' AS OTHER_STRING_COLUMN,
      NULL AS SAMPLE_CALCULATED_COLUMN

),

error_values AS (

    SELECT

    ...
    '(error)' AS OTHER_STRING_COLUMN,
    NULL AS SAMPLE_CALCULATED_COLUMN

),

ghost_records AS (
    SELECT * FROM unknown_values
    UNION ALL
    SELECT * FROM error_values
),
...
```
Expected values for the calculated string column would be '(unknown)' and '(error)'.

**Comment by tkirschke** [comment]
Hi @lwehle, 

Thanks for reaching out! I agree with the expected values. Could you try out to specify the datatype of the derived columns in a different way? My current assumption is, that the macro in the background cant identify the string, and therefore the NULL is used as datatype. 

Please change your model to this: 
```
{%- set yaml_metadata -%}
source_model: abc
derived_columns:
  SAMPLE_CALCULATED_COLUMN:
    value: "'TEST_' || ID"
    datatype: "STRING"
  OTHER_STRING_COLUMN: NAME
ldts: LOADTIMESTAMP
rsrc: '!123'
{%- endset -%}
```

If this produces the correct output, then I would know how to modify the macro. I would want the macro to work with your orignal input in the end!

Kind regards, 
Tim
