### ISSUE TITLE
Incremental loads for hubs and links don't use high-water-mark

### ISSUE THREAD

**Issue by lwehle** [ScalefreeCOM/datavault4dbt#68]
Hi,

I stumbled upon our hubs and links not using high-water-mark for their incremental loading.
For this issue I would only go into hubs since links probably share the same cause.

dbt version: 1.4.6
datavault4dbt version: 1.0.17
database: snowflake

We defined our own aliases in the dbt_project.yml
```
#Column Aliases
  datavault4dbt.ldts_alias: 'CDP_LOADDTS'
  datavault4dbt.rsrc_alias: 'CDP_RECORD_SOURCE'
```
Every stage defines these two attributes:
``` yaml
ldts: CDP_LOADDTS
rsrc: '[static source identifier]'
```
Our hub definition is very slim, as we define the matching columns (HK/BK) for the hubs in the source_models.
For multiple sources:
``` yaml
{{ config(materialized='incremental') }}
{%- set yaml_metadata -%}
hashkey: HASHKEY_SK
business_keys: BUSINESSKEY_BK
source_models:
    V_MODEL1: {}
    V_MODEL2: {}
    V_MODEL3: {}
{%- endset -%}
```
For single source hubs:
``` yaml
{{ config(materialized='incremental') }}
{%- set yaml_metadata -%}
hashkey: HASHKEY_SK
business_keys: BUSINESSKEY_BK
source_models: V_MODEL4
{%- endset -%}
```

Both definitions always process the entire history of the stage data to determine the delta. Are we missing something in the definition that is necessary to calculate the high-water-mark? 

We would like to get the same result for delta calculation analogous to the sat definition and decrease our processing time.
``` yaml
{{ config(materialized='incremental') }}
{%- set yaml_metadata -%}
source_model: V_MODEL4
parent_hashkey: HASHKEY_SK
src_hashdiff:
  source_column: S_SAT_HASHDIFF
  alias: HASHDIFF
src_payload:
  - COL1
  - COL2
{%- endset -%}
```

Kind regards,
Lars
